repository_type: pipeline
nf_core_version: "2.14"
org_path: null
lint:
  actions_ci: false
  actions_awstest: false
  actions_awsfulltest: false
  schema_lint: false
  multiqc_config: false
  files_exist:
    - .github
    - docs
